//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public Type()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int TypeID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
