//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Types = new HashSet<Type>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string author { get; set; }
        public Nullable<double> rate { get; set; }
        public string description { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public string imageUrl { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public Nullable<int> saleOff { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
        public Nullable<int> userIdCreate { get; set; }
        public Nullable<System.DateTime> dateUpdate { get; set; }
        public Nullable<int> userIdUpdate { get; set; }
        public Nullable<bool> flag { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<Type> Types { get; set; }
    }
}
