//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Books = new HashSet<Book>();
            this.Books1 = new HashSet<Book>();
            this.Orders = new HashSet<Order>();
        }
    
        public int UserID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public byte[] VisaCode { get; set; }
        public string Phone { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<bool> Flag { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
        public virtual ICollection<Book> Books1 { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Role Role { get; set; }
    }
}
